#+TITLE: Co Po

* Co - Po

** Groups
*** Winner group
*** Advance Learner Group
*** Slow Learner group
* Queries.
1) Units ?\\
 6 units
2) End semister exam.. first 2 units?\\
   YES.. for end semister exam only 2 units. Teacher said probably that what happens everytime.\\
   Stay active on social media\\
3) Textbooks?\\
   Faculties will tell you.. Go for basic books and references books.\\
   Keep ppt's of faculties.\\
4) exam pattern.\\
   not sure yet.. tell you later.\\
   30/70 pattern. with unit test. (these marks are imp).\\
5) notes right now?\\
    Yes i will tell you books and ppt's.\\
6) Next month Offline collage.\\
   Not yet decided.. No guidelines YET. corona is increasing.. they will inform with a rest period..\\
7) Another thing\\
   After this unit.. teacher will give assignments... and send pdfsss..\\
   Max 6 questions .. easy.\\
8) Last year portion skip / reduced?\\
   No portion skip for 2021-2022.\\
   It was skiped because of late addmission process.\\
   *STUDY ALL THE THINGS*. - shital patil\\
9) Exam forms?\\
   They will tell you (class teachers).\\
SHITPOINT-> people don't wear masks.\\
10) First year finishing date?\\
    can't predict right now..\\
SHITPOINT-> after jan cases always\\
11) my question.. what are mentors.\\
  asks personal questions.. and take meetings.. asks about basic things and guides..\\
  sometimes personal calling\\
   - *33-64 SHITAL PATIL* mentor..
   - *1-32 AMIT KHANDAGALE* mentor..
12) way of taking lectures\\
   most probably on projectors and a effort to take lectures in interesting way.\\
13) Signin problems?\\
   yes.. do you guys know?\\
   go to https://teams.microsoft.com/. then login there.\\
   use default passwords and stuff.\\
