#+TITLE: Unit1
#+DISCRIPTION: Resolution and compairison forces

* Sylllabus
-  Principle of statics
-  Force system, Resolution and composition of forces, Resultant concurrent forces. Moment of force.
-  varigon's Theorem, Resultant of parrel force system.
-  couple Equivalent force couple system.
-  Resultant of parrelel general force system.
* Engineeering Mechanics.
*MEANING* It is study of state of rigit body under applications of forces(external).
- Study -> *observer*, object & observations i.e it will observe physical quantity which are for example Mass, velocity force torque.
- Rigit body -> solid (rigit and deformable), Liquid and Gas.
- Forces -> It is some effect of external agent when applied to body, it can change the state of body.

** Entra point:
As a matter of fact knowledge of Engineering Mechanics is _very_ _essential_ for an engineer in *planning* *designing* and *constuction* of his various types of structure and machine.
** Units:
*** Fundamental Units
 Every quantity is measured in terms of some arbitrary, but internationally accepted units called as fundamental units.
 1. Length
 2. Mass
 3. Time.
*** Derived Units
 Sometimes, the units are also expressed in other units which are derived from fundamental units known as derived units. e.g. units of area, velocity, acceleration, pressure etc.
*** Systems of units
There are only four systems of unit which are ocmmandly used and universally recognised.
These are known as:
1. C.G.S
2. F.P.S
3. M.K.S
4. S.I
**** S.I units:
The eleventh general conference of weights and measured has recommended a unifeed and systematically constituted system of fundamental are derived its for international use. This system of units is now being used in many countries.
**** Formulas Image:
_8-11 are imp_
**** Basic Terminology
- _Mass_ : the quantity of matter possed by a body is called mass.
- _Time_ : The time is the measure of succession of events
- _Space_ : The geometric region in which study of body is involved is called space.
- _Length_ : It is concept to measure linear distances
- _Displacement_ : distance moved by a particle in a specified direction
- _Velocity_: The rate of change of Displacement with respect to time.
- _Acceleration_: Rate of change of velocity with respect to time.
- _Momentum_: Product of mass and velocity
- _Continumm_: Continuous Distribution of matter
- _Rigit Body_: A body is said to be rigit if the relative positions of any two particles do not change under the action of the forces acting on it.
- _Particle_ : A particle may be defined as an object which has only mass and no size.
